apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - imageName: jenkins-x-docker-registry:5000/jenkinsx/my-spring-boot6
    workspace: .
    dockerfilePath: Dockerfile.release
  local: {}
deploy:
  kubectl:
    manifests: