apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - imageName: $JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST:$JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT/jenkinsx/my-spring-boot6
    workspace: .
    dockerfilePath: Dockerfile.release
  local: {}
deploy:
  kubectl:
    manifests: